#ifndef CONSTANTS_HPP
#define CONSTANTS_HPP

const int GAME_WIDTH  = 400;
const int GAME_HEIGHT = 600;
const int DEBUG_PANE_WIDTH  = 400;
const int DEBUG_PANE_HEIGHT = GAME_HEIGHT;
const int SCREEN_WIDTH  = GAME_WIDTH + DEBUG_PANE_WIDTH;
const int SCREEN_HEIGHT = GAME_HEIGHT;

const double GRAVITY = 0.5;

const int CHAR_HEIGHT = 30;
const int CHAR_WIDTH = 18;
const double CHAR_JUMP_VELOCITY = 20;

const int PLATFORM_HEIGHT = 1;
const int PLATFORM_WIDTH = 50;
const int MAX_PLATFORM_Y_SPACING = 100;
const int MIN_PLATFORM_Y_SPACING = 10;

const int JUMPING_THRESHOLD_HEIGHT = SCREEN_HEIGHT/3;

#endif
